@host=https://localhost:7033
POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName" : "Engin",
    "lastName" : "YILDIRIM",
    "email" : "ey@gmail.com",
    "password" : "xxxxxx"
}