@host=https://localhost:7033
GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI2OGQxYjdmNy1jNmRkLTQ0MDAtYjhhMy04ZTVmYjI1YzA5ODMiLCJzdWIiOiI1ZjI3M2MzMy03M2EzLTQwODctODMyYy0zM2RjYTVjZmVhNmEiLCJmYW1pbHlfbmFtZSI6IllJTERJUklNIiwiZ2l2ZW5fbmFtZSI6IkVuZ2luIiwiZXhwIjoxNjc4Mjg2NDg4LCJpc3MiOiJJbXByaXZhdGVEaW5uZXIiLCJhdWQiOiJJbXByaXZhdGVEaW5uZXIifQ.cVtod56_qod9bFNZR-3QJrRRCYFq_O-Ra3735SphyK4
